db:
  name: wp-database
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: msalim22/wpdb
    tag: v2
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
      mysql: 3306
