FROM wordpress:latest
RUN apt-get update && \
  apt-get install -y mariadb-client vim
ENV WORDPRESS_DB_HOST=db
ENV WORDPRESS_DB_USER=wordpress
ENV WORDPRESS_DB_PASSWORD=wordpress
ENV WORDPRESS_DB_NAME=wordpress
EXPOSE 80
