apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ngnix.name }}
  labels:
{{- toYaml .Values.ngnix.labels | nindent 4 }}
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.ngnix.containerPorts.http }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  type: NodePort
  selector:
{{- toYaml .Values.ngnix.labels | nindent 4 }}       # Pod label that service is using to select Pods
